[package]
name = "gchconfig"
description = "CLI for GitLab Cloud Host configuration"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gchconfig"
path = "src/main.rs"

[dependencies]
clap.workspace = true
dotenvy.workspace = true
gch-core = { path = "../gch-core" }
reqwest = { workspace = true, features = ["blocking", "json"] }
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
